# fly.toml app configuration file generated for fresh4life on 2025-05-09T13:47:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fresh4life'
primary_region = 'ams'

[build]

[env]
  PORT = '8080'
  ROCKET_ADDRESS = '0.0.0.0'
  ROCKET_PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
